server:
  port: ${PORT:8082} # Railway utilisera le port dynamique, 8082 en local
  forward-headers-strategy: framework

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400

spring:
  application:
    name: auth-service

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://postgresql-fabricefanmoe.alwaysdata.net/fabricefanmoe_auth
    username: fabricefanmoe_auth
    password: Graven.2020

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

eureka:
  instance:
    prefer-ip-address: true
    # Pour afficher l'URL dynamique sur Eureka
    hostname: ${HOSTNAME:auth-service}


  client:
    service-url:
      defaultZone: https://discovery-service.up.railway.app/eureka
    # Activer le registre d'Eureka même en local
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
